services:
  # Laravel Backend (Development Server)
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: scarsoft-php
    volumes:
      - ./server:/var/www/html:cached
      - vendor:/var/www/html/vendor
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - scarsoft-network
    env_file: .env
    command: sh -c "composer install --optimize-autoloader --no-dev && php artisan serve --host=0.0.0.0 --port=8000"

  # MySQL Database
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    container_name: scarsoft-mysql
    env_file: .env
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3310:3306"
    networks:
      - scarsoft-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Node.js for React Development
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: scarsoft-frontend
    volumes:
      - ./client:/app:cached
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    networks:
      - scarsoft-network
    command: sh -c "npm install && npm run dev"

volumes:
  mysql-data:
    name: scarsoft-mysql-data
  node_modules:
  vendor:

networks:
  scarsoft-network:
    driver: bridge