
services:
  # Laravel Backend (Development Server)
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: scarsoft-php
    volumes:
      - ./server:/var/www/html:cached
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - scarsoft-network
    env_file: .env
    command: php artisan serve --host=0.0.0.0 --port=8000

  # MySQL Database
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    container_name: scarsoft-mysql
    env_file: .env
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3310:3310"
    networks:
      - scarsoft-network

  # Node.js for React Development
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: scarsoft-frontend
    volumes:
      - ./client:/app:cached
    ports:
      - "5173:5173"
    networks:
      - scarsoft-network

volumes:
  mysql-data:
    name: scarsoft-mysql-data

networks:
  scarsoft-network:
    driver: bridge